HOMEPAGE = "http://www.ubuntu.org"
# This LICENSE entry really needs to be fixed. Ubuntu passes through
# open source software and we have an aggregated set of open source
# licenses that is hard to characterize. If anyone can suggest a proper
# way to fix this, please do so! The MIT related entry is borrowed
# from the merge-files recipe to show intent of passing through
# files from other origins in a proper fashion.
# <Heinz.Wrobel@nxp.com>
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/GPL-2.0-only;md5=801f80980d171dd6425610833a22dbe6 \
                    file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"
