# Provides the base settings for LS2

CW_PATH ?= "/opt/Freescale/CW4NET_v2015.05/CW_APP"

GCCVERSION = "linaro-4.8"
BINUVERSION = "linaro-2.24"
PREFERRED_VERSION_eglibc = "linaro-2.19"
PREFERRED_VERSION_nativesdk-eglibc = "linaro-2.19"
PREFERRED_VERSION_quagga = "0.99.9"
PREFERRED_VERSION_qemu = "2.3+fsl"
PREFERRED_VERSION_libvirt = "1.2.13"
PREFERRED_VERSION_python = "2.7.9"
PREFERRED_VERSION_python-native = "2.7.9"

# whitelisted restricted license
LICENSE_FLAGS_WHITELIST = "non-commercial_netperf"
